import type { Category, Submission } from './types'

export const CATEGORIES: Category[] = [
  {
    slug: 'celebrity',
    name: 'Celebrity Spotting',
    icon: 'star',
    blurb: 'A-listers off-duty, on red carpets and out and about.',
    payout: '£50 – £5,000',
    accent: '#f43f5e',
  },
  {
    slug: 'breaking-news',
    name: 'Breaking News',
    icon: 'newspaper',
    blurb: 'You saw it first. Send it to the newsroom in seconds.',
    payout: '£100 – £10,000',
    accent: '#ef4444',
  },
  {
    slug: 'crime',
    name: 'Crime',
    icon: 'gavel',
    blurb: 'Incidents, scenes and aftermath. Keep yourself safe.',
    payout: '£75 – £4,000',
    accent: '#dc2626',
  },
  {
    slug: 'local-crime',
    name: 'Local Crime',
    icon: 'location_city',
    blurb: 'Antisocial behaviour, vandalism, theft on your street.',
    payout: '£25 – £750',
    accent: '#fb7185',
  },
  {
    slug: 'police',
    name: 'Police Spotting',
    icon: 'local_police',
    blurb: 'Active scenes, vehicles, raids — keep your distance.',
    payout: '£40 – £1,500',
    accent: '#1d4ed8',
  },
  {
    slug: 'events',
    name: 'Events',
    icon: 'celebration',
    blurb: 'Festivals, protests, parades and reunions.',
    payout: '£30 – £2,000',
    accent: '#a855f7',
  },
  {
    slug: 'weather',
    name: 'Weather',
    icon: 'thunderstorm',
    blurb: 'Storms, snow, floods, dramatic skies.',
    payout: '£20 – £1,200',
    accent: '#0891b2',
  },
  {
    slug: 'sport',
    name: 'Sport',
    icon: 'sports_soccer',
    blurb: 'Match action, fan moments and behind the scenes.',
    payout: '£40 – £3,000',
    accent: '#16a34a',
  },
]

export function getCategory(slug: string) {
  return CATEGORIES.find((c) => c.slug === slug)
}

const ph = (seed: string, w = 800, h = 600) =>
  `https://picsum.photos/seed/${encodeURIComponent(seed)}/${w}/${h}`

export const SAMPLE_SUBMISSIONS: Submission[] = [
  {
    id: 'demo-1',
    title: 'Pop star spotted leaving Soho restaurant',
    description:
      'Caught coming out the back exit at around 11pm with two minders. Several other diners were present.',
    category: 'celebrity',
    location: 'Soho, London',
    askingPrice: 450,
    status: 'sold',
    earnings: 620,
    views: 12480,
    mediaType: 'image',
    mediaUrl: ph('celeb-soho'),
    createdAt: Date.now() - 1000 * 60 * 60 * 4,
    authorId: 'demo-user-1',
    authorName: 'Jamie R.',
    exclusive: true,
  },
  {
    id: 'demo-2',
    title: 'Major fire on industrial estate',
    description: 'Heavy plumes of smoke visible from the M62. Six fire engines on scene.',
    category: 'breaking-news',
    location: 'Manchester',
    askingPrice: 800,
    status: 'sold',
    earnings: 1450,
    views: 28900,
    mediaType: 'image',
    mediaUrl: ph('fire-mcr'),
    createdAt: Date.now() - 1000 * 60 * 60 * 8,
    authorId: 'demo-user-2',
    authorName: 'Sarah K.',
    exclusive: true,
  },
  {
    id: 'demo-3',
    title: 'Armed police response in city centre',
    description: 'Three armed response vehicles outside the shopping centre. Cordon set up.',
    category: 'police',
    location: 'Birmingham',
    askingPrice: 300,
    status: 'approved',
    earnings: 0,
    views: 980,
    mediaType: 'image',
    mediaUrl: ph('police-bham'),
    createdAt: Date.now() - 1000 * 60 * 60 * 14,
    authorId: 'demo-user-3',
    authorName: 'Tom B.',
    exclusive: false,
  },
  {
    id: 'demo-4',
    title: 'Storm Erin batters seafront',
    description: 'Waves crashing over promenade. People being knocked off their feet.',
    category: 'weather',
    location: 'Brighton',
    askingPrice: 220,
    status: 'sold',
    earnings: 340,
    views: 18200,
    mediaType: 'image',
    mediaUrl: ph('storm-bton'),
    createdAt: Date.now() - 1000 * 60 * 60 * 22,
    authorId: 'demo-user-4',
    authorName: 'Priya N.',
    exclusive: false,
  },
  {
    id: 'demo-5',
    title: 'Vandalism at local park overnight',
    description: 'Climbing frame and toilets covered in graffiti. Bins set on fire.',
    category: 'local-crime',
    location: 'Leeds',
    askingPrice: 90,
    status: 'pending',
    earnings: 0,
    views: 220,
    mediaType: 'image',
    mediaUrl: ph('vandal-leeds'),
    createdAt: Date.now() - 1000 * 60 * 60 * 28,
    authorId: 'demo-user-5',
    authorName: 'Conor M.',
    exclusive: false,
  },
  {
    id: 'demo-6',
    title: 'Premier League striker leaving training',
    description: 'Brief stop to sign autographs. Clear shots from the car park.',
    category: 'sport',
    location: 'Liverpool',
    askingPrice: 380,
    status: 'sold',
    earnings: 510,
    views: 9400,
    mediaType: 'image',
    mediaUrl: ph('striker-lfc'),
    createdAt: Date.now() - 1000 * 60 * 60 * 33,
    authorId: 'demo-user-6',
    authorName: 'Mel A.',
    exclusive: true,
  },
  {
    id: 'demo-7',
    title: 'Pride parade — front row footage',
    description: 'Two minutes of crowd reaction and float close-ups.',
    category: 'events',
    location: 'Bristol',
    askingPrice: 160,
    status: 'approved',
    earnings: 0,
    views: 4100,
    mediaType: 'image',
    mediaUrl: ph('pride-brs'),
    createdAt: Date.now() - 1000 * 60 * 60 * 41,
    authorId: 'demo-user-7',
    authorName: 'Alex W.',
    exclusive: false,
  },
  {
    id: 'demo-8',
    title: 'Suspect detained outside off-licence',
    description: 'Two officers, one suspect on the ground. Witnesses gathering.',
    category: 'crime',
    location: 'Glasgow',
    askingPrice: 250,
    status: 'sold',
    earnings: 320,
    views: 6700,
    mediaType: 'image',
    mediaUrl: ph('arrest-gla'),
    createdAt: Date.now() - 1000 * 60 * 60 * 50,
    authorId: 'demo-user-8',
    authorName: 'Hannah D.',
    exclusive: false,
  },
]
